// netlify/functions/recommendations-api.mts
//
// Auth-protected Coach-mode recommendations endpoint.
//
// GET /.netlify/functions/recommendations-api?category=crypto
//                                            &halfLife=50           (optional)
//                                            &windowDays=30         (optional)
//
// Returns the per-bot recommendation list generated by
// `auto-trader/shared/recommendations.mts`. The endpoint reads the same
// closed-trade store the Edge Tracker uses, applies the current Settings
// overrides as `effective` baseline, and dispatches into the per-category
// engine.
//
// Apply flow: the UI POSTs the suggested value to `/trader-settings` (the
// existing Settings endpoint). This endpoint is GET-only, never mutates
// state.
//
// Auth: anonymous reads receive the `insufficient-data` placeholder so
// the panel still renders something on unauth'd visits, but the actual
// rule output requires a JWT. Mirrors the Settings tab visibility model
// (defaults exposed publicly, live overrides only authed).

import type { Context } from "@netlify/functions";
import { getStore } from "@netlify/blobs";
import { checkAuth } from "./_auth-guard.ts";
import type { ClosedTrade, SessionState } from "./auto-trader/shared/types.mts";
import {
  generateRecommendations,
  DEFAULT_HALF_LIFE,
  type RecommendationCategory,
} from "./auto-trader/shared/recommendations.mts";

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
  "Content-Type": "application/json",
};

// Per-category Blobs source. Mirrors the Edge Tracker STORE_SPECS so the
// same trades that show up there feed the recommendations engine.
interface StoreSpec {
  store:    string;
  paperKey: string;
  category: RecommendationCategory;
}

const STORE_SPECS: StoreSpec[] = [
  { store: "auto-trader-state",          paperKey: "auto-trader-session",         category: "crypto"      },
  { store: "auto-trader-state",          paperKey: "auto-trader-session-weather", category: "weather"     },
  { store: "hyperliquid-session-v1",     paperKey: "session_paper",               category: "hyperliquid" },
  { store: "hyperliquid-arb-session-v1", paperKey: "arb_paper",                   category: "funding-arb" },
];

const VALID_CATEGORIES: RecommendationCategory[] = ["crypto", "weather", "hyperliquid", "funding-arb"];

// ─── Trade extraction (per-category shape) ───────────────────────────────

interface RawSession {
  closedTrades?: any[];
  positions?:    any[];
  bankrollStart?: number;
  bankrollCurrent?: number;
  stopped?: boolean;
  stoppedReason?: string | null;
  calibrationAlertSentAt?: string | null;
}

function normalizeHlTrade(t: any): ClosedTrade {
  return {
    market:        String(t.coin ?? ""),
    direction:     t.direction as any,
    entryPrice:    Number(t.entryPrice ?? 0),
    exitPrice:     Number(t.exitPrice ?? 0),
    shares:        Number(t.sizeCoins ?? 0),
    pnl:           Number(t.pnlUSDC ?? 0),
    pnlPct:        Number(t.pnlPct ?? 0) * 100,
    openedAt:      t.openedAt,
    closedAt:      t.closedAt,
    category:      "hyperliquid" as any,
    predictedProb: t.predictedProb,
    edgeAtEntry:   t.edgeAtEntry,
    signalBreakdown: t.signalBreakdown,
  };
}

function extractTrades(raw: RawSession, category: RecommendationCategory): ClosedTrade[] {
  const out: ClosedTrade[] = [];
  if (Array.isArray(raw.closedTrades)) {
    for (const t of raw.closedTrades) {
      if (category === "hyperliquid") {
        out.push(normalizeHlTrade(t));
      } else {
        out.push({ ...t, category: t.category ?? category });
      }
    }
  }
  // F-Arb shape: positions[] with closedAt + closeFundingNet.
  if (category === "funding-arb" && Array.isArray(raw.positions)) {
    for (const p of raw.positions) {
      if (!p?.closedAt) continue;
      out.push({
        market:               String(p.coin || "funding-arb"),
        direction:            "NO" as any,
        entryPrice:           Number(p.hlEntryPrice ?? 0),
        exitPrice:            0,
        shares:               Number(p.sizeCoins ?? 0),
        pnl:                  Number(p.closeFundingNet ?? 0),
        pnlPct:               p.sizeUSDC > 0
                                ? (Number(p.closeFundingNet ?? 0) / Number(p.sizeUSDC)) * 100
                                : 0,
        openedAt:             p.openedAt,
        closedAt:             p.closedAt,
        category:             "funding-arb" as any,
        edgeAtEntry:          Number(p.entrySpread ?? 0),
      } as ClosedTrade);
    }
  }
  return out;
}

// ─── Effective Settings loader ───────────────────────────────────────────

async function loadEffective(): Promise<Record<string, number>> {
  try {
    const mod: any = await import("./trader-settings.mts");
    const ov = (await mod.loadRuntimeOverrides()) ?? {};
    // Note: we don't merge with SCHEMA defaults here — the recommendations
    // engine uses `??` with its own defaults per-field, which matches the
    // SCHEMA defaults. Operator overrides take precedence.
    return ov as Record<string, number>;
  } catch {
    return {};
  }
}

// ─── Main handler ────────────────────────────────────────────────────────

export default async function handler(req: Request, _ctx: Context) {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS });
  if (req.method !== "GET")     return new Response(JSON.stringify({ ok: false, reason: "method_not_allowed" }), { status: 405, headers: CORS });

  const url = new URL(req.url);
  const categoryParam = (url.searchParams.get("category") ?? "crypto") as RecommendationCategory;
  const halfLifeParam = url.searchParams.get("halfLife");
  const windowDaysParam = url.searchParams.get("windowDays");

  if (!VALID_CATEGORIES.includes(categoryParam)) {
    return new Response(
      JSON.stringify({ ok: false, reason: `Unknown category: ${categoryParam}. Valid: ${VALID_CATEGORIES.join(", ")}` }),
      { status: 400, headers: CORS },
    );
  }

  // Auth gate. Anonymous gets the no-data placeholder.
  const auth = await checkAuth(req);
  if (!auth.ok) {
    return new Response(
      JSON.stringify({
        ok: true,
        category: categoryParam,
        generatedAt: new Date().toISOString(),
        tradeCount: 0,
        closedTradeWindow: "all",
        halfLifeTradesUsed: null,
        recommendations: [{
          id:             "rec-auth-required",
          field:          null,
          currentValue:   null,
          suggestedValue: null,
          severity:       "info",
          confidence:     "low",
          title:          "Bejelentkezés szükséges a javaslatok megtekintéséhez",
          reasoning:      "A Coach-mode recommendations a closed-trade adatokra épülnek, amelyek auth-protected. Jelentkezz be a Settings tabon.",
          dataPoints:     {},
        }],
        authed: false,
      }),
      { status: 200, headers: CORS },
    );
  }

  // Resolve half-life (optional override; defaults to DEFAULT_HALF_LIFE).
  let halfLifeTrades: number | null = DEFAULT_HALF_LIFE;
  if (halfLifeParam !== null) {
    const parsed = parseFloat(halfLifeParam);
    halfLifeTrades = (Number.isFinite(parsed) && parsed > 0) ? parsed : null;
  }

  // Load closed trades from the matching store.
  const spec = STORE_SPECS.find((s) => s.category === categoryParam)!;
  let trades: ClosedTrade[] = [];
  let session: Partial<SessionState> = {};
  try {
    const store = getStore(spec.store);
    const raw = await store.get(spec.paperKey);
    if (raw) {
      const parsed = JSON.parse(raw as string) as RawSession;
      trades = extractTrades(parsed, categoryParam);
      session = {
        bankrollStart:           parsed.bankrollStart ?? 100,
        bankrollCurrent:         parsed.bankrollCurrent ?? parsed.bankrollStart ?? 100,
        stopped:                 !!parsed.stopped,
        stoppedReason:           parsed.stoppedReason ?? null,
        calibrationAlertSentAt:  parsed.calibrationAlertSentAt ?? null,
      } as Partial<SessionState>;
    }
  } catch {
    // Soft-fail — empty trades → engine returns insufficient-data item.
  }

  // Optional time window filter (default: all).
  let closedTradeWindow = "all";
  if (windowDaysParam) {
    const n = parseInt(windowDaysParam, 10);
    if (Number.isFinite(n) && n > 0) {
      const cutoff = Date.now() - n * 86_400_000;
      trades = trades.filter((t) => {
        const k = new Date(t.closedAt ?? 0).getTime();
        return Number.isFinite(k) && k >= cutoff;
      });
      closedTradeWindow = `last ${n}d`;
    }
  }

  const effective = await loadEffective();
  const recs = generateRecommendations(categoryParam, {
    trades,
    session: session as any,
    effective,
    halfLifeTrades,
  });

  return new Response(
    JSON.stringify({
      ok:                 true,
      category:           categoryParam,
      generatedAt:        new Date().toISOString(),
      tradeCount:         trades.length,
      closedTradeWindow,
      halfLifeTradesUsed: halfLifeTrades,
      recommendations:    recs,
      authed:             true,
    }),
    { status: 200, headers: CORS },
  );
}
